// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Pokemon struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Image  string `json:"image"`
	Height *int   `json:"height,omitempty"`
	Weight *int   `json:"weight,omitempty"`
}
